"""create_all_tables_with_associations

Revision ID: 9556c70adcc8
Revises: 9f9d031d1c34
Create Date: 2025-07-14 15:21:44.799015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9556c70adcc8'
down_revision = '9f9d031d1c34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('constraint_type', sa.Enum('HARD', 'SOFT', name='constrainttype'), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_global_constraints_id'), 'global_constraints', ['id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CLASSROOM', 'LAB', 'GYM', 'MUSIC', 'ART', 'COMPUTER', 'LIBRARY', 'AUDITORIUM', name='roomtype'), nullable=True),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('is_accessible', sa.Boolean(), nullable=True),
    sa.Column('has_air_conditioning', sa.Boolean(), nullable=True),
    sa.Column('has_windows', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_code'), 'rooms', ['code'], unique=True)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name_he', sa.String(length=255), nullable=False),
    sa.Column('name_fr', sa.String(length=255), nullable=False),
    sa.Column('subject_type', sa.Enum('ACADEMIC', 'SPORTS', 'ARTS', 'RELIGIOUS', 'LANGUAGE', 'SCIENCE_LAB', name='subjecttype'), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_lab', sa.Boolean(), nullable=True),
    sa.Column('requires_special_room', sa.Boolean(), nullable=True),
    sa.Column('requires_consecutive_hours', sa.Boolean(), nullable=True),
    sa.Column('max_hours_per_day', sa.Integer(), nullable=True),
    sa.Column('is_religious', sa.Boolean(), nullable=True),
    sa.Column('requires_gender_separation', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('max_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('max_hours_per_day', sa.Integer(), nullable=True),
    sa.Column('prefers_consecutive_hours', sa.Boolean(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('primary_language', sa.String(length=2), nullable=True),
    sa.Column('can_teach_in_french', sa.Boolean(), nullable=True),
    sa.Column('can_teach_in_hebrew', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_code'), 'teachers', ['code'], unique=True)
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('language_preference', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('class_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('grade_name', sa.String(length=50), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('class_type', sa.Enum('REGULAR', 'ADVANCED', 'SPECIAL_NEEDS', name='classtype'), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('preferred_schedules', sa.JSON(), nullable=True),
    sa.Column('is_boys_only', sa.Boolean(), nullable=True),
    sa.Column('is_girls_only', sa.Boolean(), nullable=True),
    sa.Column('is_mixed', sa.Boolean(), nullable=True),
    sa.Column('primary_language', sa.String(length=2), nullable=True),
    sa.Column('homeroom_teacher_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['homeroom_teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_groups_code'), 'class_groups', ['code'], unique=True)
    op.create_index(op.f('ix_class_groups_id'), 'class_groups', ['id'], unique=False)
    op.create_table('room_unavailabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', name='dayofweek'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'day_of_week', 'start_time', 'end_time', name='uq_room_unavailability')
    )
    op.create_index(op.f('ix_room_unavailabilities_id'), 'room_unavailabilities', ['id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('generation_time_seconds', sa.Float(), nullable=True),
    sa.Column('solver_status', sa.String(), nullable=True),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('conflicts_json', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('parent_schedule_id', sa.Integer(), nullable=True),
    sa.Column('ai_modifications', sa.JSON(), nullable=True),
    sa.Column('manual_modifications', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_table('teacher_availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', name='dayofweek'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'day_of_week', 'start_time', 'end_time', name='uq_teacher_availability')
    )
    op.create_index(op.f('ix_teacher_availabilities_id'), 'teacher_availabilities', ['id'], unique=False)
    op.create_table('teacher_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('preference_type', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_preferences_id'), 'teacher_preferences', ['id'], unique=False)
    op.create_table('teacher_subjects',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'subject_id')
    )
    op.create_table('class_mandatory_subjects',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'subject_id')
    )
    op.create_table('class_preferred_rooms',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('preference_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'room_id')
    )
    op.create_table('class_subject_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('preferred_teacher_id', sa.Integer(), nullable=True),
    sa.Column('requires_double_period', sa.Boolean(), nullable=True),
    sa.Column('max_per_day', sa.Integer(), nullable=True),
    sa.Column('min_days_between', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['preferred_teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'subject_id', name='uq_class_subject')
    )
    op.create_index(op.f('ix_class_subject_requirements_id'), 'class_subject_requirements', ['id'], unique=False)
    op.create_table('schedule_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('conflict_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('involved_entries', sa.JSON(), nullable=True),
    sa.Column('constraint_details', sa.JSON(), nullable=True),
    sa.Column('resolution_suggestions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_conflicts_id'), 'schedule_conflicts', ['id'], unique=False)
    op.create_table('schedule_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('is_double_period', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('modified_by_ai', sa.Boolean(), nullable=True),
    sa.Column('modification_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_entries_id'), 'schedule_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_entries_id'), table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_index(op.f('ix_schedule_conflicts_id'), table_name='schedule_conflicts')
    op.drop_table('schedule_conflicts')
    op.drop_index(op.f('ix_class_subject_requirements_id'), table_name='class_subject_requirements')
    op.drop_table('class_subject_requirements')
    op.drop_table('class_preferred_rooms')
    op.drop_table('class_mandatory_subjects')
    op.drop_table('teacher_subjects')
    op.drop_index(op.f('ix_teacher_preferences_id'), table_name='teacher_preferences')
    op.drop_table('teacher_preferences')
    op.drop_index(op.f('ix_teacher_availabilities_id'), table_name='teacher_availabilities')
    op.drop_table('teacher_availabilities')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_room_unavailabilities_id'), table_name='room_unavailabilities')
    op.drop_table('room_unavailabilities')
    op.drop_index(op.f('ix_class_groups_id'), table_name='class_groups')
    op.drop_index(op.f('ix_class_groups_code'), table_name='class_groups')
    op.drop_table('class_groups')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_code'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_code'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_global_constraints_id'), table_name='global_constraints')
    op.drop_table('global_constraints')
    # ### end Alembic commands ### 