"""Enhanced ClassGroups and Rooms models

Revision ID: ae752a6c2082
Revises: 52720f5c6cbb
Create Date: 2025-06-09 12:48:51.112689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae752a6c2082'
down_revision = '52720f5c6cbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_group_subjects',
    sa.Column('class_group_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('class_group_id', 'subject_id')
    )
    op.add_column('class_groups', sa.Column('nom', sa.String(length=255), nullable=False))
    op.add_column('class_groups', sa.Column('niveau', sa.String(length=50), nullable=False))
    op.add_column('class_groups', sa.Column('effectif', sa.Integer(), nullable=False))
    op.add_column('class_groups', sa.Column('horaires_preferes', sa.JSON(), nullable=True))
    op.add_column('class_groups', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('class_groups', sa.Column('academic_year', sa.String(length=20), nullable=True))
    op.add_column('class_groups', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('class_groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('class_groups', 'grade',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('class_groups', 'student_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'class_groups', 'teachers', ['homeroom_teacher_id'], ['id'])
    op.add_column('rooms', sa.Column('nom', sa.String(length=255), nullable=False))
    op.add_column('rooms', sa.Column('capacite', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('type_salle', sa.Enum('REGULAR_CLASSROOM', 'SCIENCE_LAB', 'COMPUTER_LAB', 'SPORTS_HALL', 'ART_ROOM', 'MUSIC_ROOM', 'LIBRARY', 'PRAYER_ROOM', 'AUDITORIUM', 'CONFERENCE_ROOM', 'LABORATORY', name='roomtype'), nullable=False))
    op.add_column('rooms', sa.Column('location_details', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('equipements', sa.JSON(), nullable=True))
    op.add_column('rooms', sa.Column('disponibilites', sa.JSON(), nullable=True))
    op.add_column('rooms', sa.Column('is_bookable', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('requires_supervision', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('maintenance_notes', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('last_maintenance', sa.String(length=50), nullable=True))
    op.alter_column('rooms', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rooms', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_subjects_new_code', table_name='subjects')
    op.drop_index('ix_subjects_new_id', table_name='subjects')
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.create_index('ix_subjects_new_id', 'subjects', ['id'], unique=False)
    op.create_index('ix_subjects_new_code', 'subjects', ['code'], unique=1)
    op.alter_column('rooms', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rooms', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('rooms', 'last_maintenance')
    op.drop_column('rooms', 'maintenance_notes')
    op.drop_column('rooms', 'description')
    op.drop_column('rooms', 'requires_supervision')
    op.drop_column('rooms', 'is_bookable')
    op.drop_column('rooms', 'disponibilites')
    op.drop_column('rooms', 'equipements')
    op.drop_column('rooms', 'location_details')
    op.drop_column('rooms', 'type_salle')
    op.drop_column('rooms', 'capacite')
    op.drop_column('rooms', 'nom')
    op.drop_constraint(None, 'class_groups', type_='foreignkey')
    op.alter_column('class_groups', 'student_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('class_groups', 'grade',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('class_groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('class_groups', 'is_active')
    op.drop_column('class_groups', 'academic_year')
    op.drop_column('class_groups', 'description')
    op.drop_column('class_groups', 'horaires_preferes')
    op.drop_column('class_groups', 'effectif')
    op.drop_column('class_groups', 'niveau')
    op.drop_column('class_groups', 'nom')
    op.drop_table('class_group_subjects')
    # ### end Alembic commands ### 